client_1:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  train:
    optimizer:
      lr: 0.1
  eval:
    metrics: ['imp_ratio','acc']
    base: 0.263789
client_2:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  train:
    optimizer:
      lr: 0.01
  eval:
    metrics: ['imp_ratio','acc']
    base: 0.289617
client_3:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  train:
    optimizer:
      lr: 0.001
  eval:
    metrics: ['imp_ratio','acc']
    base: 0.355404
client_4:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  train:
    optimizer:
      lr: 0.01
  eval:
    metrics: ['imp_ratio','acc']
    base: 0.176471
client_5:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  train:
    optimizer:
      lr: 0.0001
  eval:
    metrics: ['imp_ratio','acc']
    base: 0.396825
client_6:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  train:
    optimizer:
      lr: 0.0005
  eval:
    metrics: ['imp_ratio','acc']
    base: 0.261580
client_7:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  train:
    optimizer:
      lr: 0.01
  eval:
    metrics: ['imp_ratio','acc']
    base: 0.302378
client_8:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  train:
    optimizer:
      lr: 0.05
  eval:
    metrics: ['imp_ratio','acc']
    base: 0.211538
