use_gpu: True
device: 0
early_stop:
  delta: 0.0
  patience: 20
  improve_indicator_mode: mean
  the_smaller_the_better: False
federate:
  mode: 'standalone'
  make_global_eval: False
  total_round_num: 500
  share_local_model: False
  client_num: 8
  method: gcflplus  # ep1和ep2参数值得调一调
#fedopt:
#  use: True
#fedprox:
#  use: True
#  mu: 1.0
data:
  root: data/
  type: cikmcup
  batch_size: 64
  shuffle: True
  num_workers: 0
personalization:
  local_param: ['encoder_atom', 'encoder', 'clf', 'bn', 'norms']
train:
  batch_or_epoch: epoch
  local_update_steps: 3
  optimizer:
    type: SGD
    weight_decay: 0.0005
trainer:
  type: graphminibatch_trainer
model:
  type: gin
  task: graph
  hidden: 64
  dropout: 0.5
grad:
  grad_clip: 0.5
eval:
  freq: 10
  metrics: ['imp_ratio']
  report: ['avg']
  best_res_update_round_wise_key: val_imp_ratio
  count_flops: False
  split: ['test', 'val']
  base: 0.